Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "app01"
    config.vm.network "private_network", ip: "192.168.1.3"
    config.vm.network "fowarded_port", guest: 8080, host: 8080
  end
  